#Numpy
- Numpy is a numerical computing library for python.
- Numpy support multi dimensional arrays and matrices
- It has a lot of in-built mathematical functions

In [1]:
# installing numpy library
# ! when need to run in terminal
!pip install numpy

In [1]:
import numpy as np

#Why Numpy?
- perfomrs fast operations (because of Vectorization)
- numpy arrays can be treated as vectors and matrices from linear algebra

In [5]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
%timeit [i**2 for i in lst]


2.75 µs ± 34 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
array = np.array(lst)

In [10]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
%timeit array**2

872 ns ± 248 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1]

In [14]:
array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

#Numpy arrays
array: Fundamental element is homogenous array. Numpy Arrays can be 1D, 2D, 3D....nD

- Different ways to create np array
1. np.array()
2. np.arange()

In [17]:
l = [1, 5, 8, 9]
np_arr = np.array(l)

In [18]:
np_arr

array([1, 5, 8, 9])

In [19]:
type(np_arr)

numpy.ndarray

In [20]:
np_arr.ndim

1

In [21]:
# important
np_arr.shape


(4,)

# Another way of creating np array

In [22]:
new_arr = np.arange(3, 11, 2)

In [23]:
new_arr

array([3, 5, 7, 9])

In [24]:
lst_2d = [[1,2,3], [4, 5, 6], [7, 8, 9]]

In [25]:
arr_2d = np.array(lst_2d)

In [26]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr_2d.ndim

2

In [28]:
arr_2d.shape

(3, 3)

# Special Arrays in Numpy
- zeros()
- ones()
- diag()
- identity()

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Indexing in Array

In [2]:
np.random.randint(10, 100)

23

In [3]:
new_arr = np.random.randint(10, 100, (5,4))

In [4]:
new_arr

array([[21, 12, 88, 86],
       [62, 58, 29, 81],
       [61, 41, 22, 52],
       [69, 16, 58, 31],
       [91, 63, 74, 66]])

In [5]:
# first row
new_arr[0]

array([21, 12, 88, 86])

In [6]:
# second last row
new_arr[-2]

array([69, 16, 58, 31])

In [7]:
# first element
print(new_arr[0, 0])

#last element
print(new_arr[-1, -1])

21
66


#Array Slicing
new_arr[start_row_Count: end_row_Count, start_col_Count: end_col_Count]


In [8]:
new_arr

array([[21, 12, 88, 86],
       [62, 58, 29, 81],
       [61, 41, 22, 52],
       [69, 16, 58, 31],
       [91, 63, 74, 66]])

In [11]:
new_arr[0:2, 0:2]

array([[21, 12],
       [62, 58]])

In [12]:
new_arr[0:2, 0:]

array([[21, 12, 88, 86],
       [62, 58, 29, 81]])

In [13]:
new_arr[0:, 0:2]

array([[21, 12],
       [62, 58],
       [61, 41],
       [69, 16],
       [91, 63]])

In [14]:
# all row last col
new_arr[:, -1]

array([86, 81, 52, 31, 66])

In [15]:
#replacing element in array
new_arr[0, 0] = 0

In [16]:
new_arr

array([[ 0, 12, 88, 86],
       [62, 58, 29, 81],
       [61, 41, 22, 52],
       [69, 16, 58, 31],
       [91, 63, 74, 66]])

In [17]:
#masking
mask = new_arr > 50
print(mask)

[[False False  True  True]
 [ True  True False  True]
 [ True False False  True]
 [ True False  True False]
 [ True  True  True  True]]


In [18]:
# no of element greater than 50
np.sum(mask)

13

In [19]:
#get all the values greater than 50
new_arr[mask]

array([88, 86, 62, 58, 81, 61, 52, 69, 58, 91, 63, 74, 66])

In [20]:
new_arr

array([[ 0, 12, 88, 86],
       [62, 58, 29, 81],
       [61, 41, 22, 52],
       [69, 16, 58, 31],
       [91, 63, 74, 66]])

In [22]:
new_arr[2:, 2:] = 0

In [23]:
new_arr

array([[ 0, 12, 88, 86],
       [62, 58, 29, 81],
       [61, 41,  0,  0],
       [69, 16,  0,  0],
       [91, 63,  0,  0]])

# Basic Operations in Arrays

In [24]:
a = np.array([10, 20, 30, 40])
b = np.arange(1, 5)

In [25]:
a

array([10, 20, 30, 40])

In [26]:
b

array([1, 2, 3, 4])

In [27]:
a+b

array([11, 22, 33, 44])

In [28]:
a-b

array([ 9, 18, 27, 36])

In [29]:
a*b

array([ 10,  40,  90, 160])

In [30]:
a/b

array([10., 10., 10., 10.])

In [31]:
a//b

array([10, 10, 10, 10])

In [32]:
b**2

array([ 1,  4,  9, 16])

In [36]:
#masking
mask = a > 15
print(mask)

[False  True  True  True]


In [37]:
sum(mask)

3

In [38]:
a[mask]

array([20, 30, 40])

In [39]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [40]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

#Matrix Product


In [41]:
A = np.random.randint(0, 5, (3, 4))
B = np.random.randint(2, 8, (4, 2))

In [42]:
A

array([[3, 2, 2, 2],
       [1, 3, 4, 1],
       [0, 0, 3, 1]])

In [43]:
B

array([[3, 3],
       [6, 2],
       [4, 5],
       [6, 3]])

In [45]:
#Dot Product
np.dot(A, B)

array([[41, 29],
       [43, 32],
       [18, 18]])